apiVersion: v1
kind: Template
metadata:
  name: "mysql"
  annotations:
    openshift.io/display-name: MySql
    iconClass: icon-codeigniter
    description: This will deploy a functional vanilla liferay 7 with a persisten storage and a database
      and exposed public as <deployment-name>.firelay.managed.services
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${DEPLOYMENT_NAME}-mysql
    labels:
      app: ${DEPLOYMENT_NAME}-mysql
      tier: mysql
  data:
    my.cnf: |-
      [client]
      port   = 3306
      socket   = /var/run/mysqld/mysqld.sock
      default-character-set=utf8

      default-character-set=utf8
      [mysql]
      [mysqld_safe]
      pid-file = /var/run/mysqld/mysqld.pid
      socket   = /var/run/mysqld/mysqld.sock
      nice   = 0
      [mysqld]
      user   = mysql
      pid-file = /var/run/mysqld/mysqld.pid
      socket   = /var/run/mysqld/mysqld.sock
      port   = 3306
      basedir    = /usr
      datadir    = /var/lib/mysql
      tmpdir   = /tmp
      lc-messages-dir  = /usr/share/mysql
      explicit_defaults_for_timestamp
      collation-server = utf8_general_ci
      init-connect='SET NAMES utf8'
      character-set-server = utf8
      log-error  = /var/log/mysql/error.log
      # Recommended in standard MySQL setup
      sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
      # Disabling symbolic-links is recommended to prevent assorted security risks
      symbolic-links=0
      # This increase of max_connections from the default of 151 to 1024 has been
      # tested as adequate for an environment with up to 24 API/Worker/Collector
      # components (8 of each) and 4000 Agents of incoming traffic. The MySQL
      # container also consumed as much as 1 GB of memory in this test.
      max_connections=1024
      !includedir /etc/mysql/conf.d/
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${DEPLOYMENT_NAME}-mysql
    labels:
      app: ${DEPLOYMENT_NAME}-mysql
      tier: mysql
  data:
    password: bGlmZXJheWRldg==
- apiVersion: v1
  kind: Service
  metadata:
    name: ${DEPLOYMENT_NAME}-mysql
    labels:
      app: ${DEPLOYMENT_NAME}-mysql
      tier: mysql
  spec:
    ports:
      - port: 3306
    selector:
      app: ${DEPLOYMENT_NAME}-mysql
      tier: mysql
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: ${DEPLOYMENT_NAME}-mysql
  spec:
    template:
      metadata:
        labels:
          app: ${DEPLOYMENT_NAME}-mysql
          tier: mysql
      spec:
        containers:
          - name: mysql
            image: registry.access.redhat.com/rhscl/mysql-56-rhel7
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: ${DEPLOYMENT_NAME}-mysql
                    key: password
              - name: MYSQL_USER
                value: liferay
              - name: MYSQL_PASSWORD
                value: liferay
              - name: MYSQL_DATABASE
                value: ${DEPLOYMENT_NAME}
            volumeMounts:
              - name: mysql-config
                mountPath: /etc/mysql/my.cnf
                subPath: my.cnf
              - name: data
                mountPath: /var/lib/mysql
        volumes:
          - name: mysql-config
            configMap:
              name: ${DEPLOYMENT_NAME}-mysql
          - name: data
            emptyDir: {}
parameters:
  - name: DEPLOYMENT_NAME
    description: Name of deployment
    required: true
    value: mysql
